#!/bin/sh

# desktop

if [[ $(xrandr -q | grep 'HDMI2 connected') ]]; then
    xrandr --output eDP1 --mode 1920x1080 --pos 0x360 --output HDMI2 --primary --mode 2560x1440 --pos 1920x0 && bspc monitor HDMI2 -d z x c v && bspc monitor eDP1 -d 1 2 3 4 && export TRAY_POS_SECOND=left
else
    xrandr --output eDP1 --primary --mode 1920x1080 && bspc monitor eDP1 -d z x c v && export TRAY_POS_MAIN=left
fi
bspc desktop -f 'z'
feh --bg-fill ~/.dotfiles/wallpaper.jpg
picom & disown

# bar

$HOME/.config/polybar/launch.sh & disown

# bswm config

pgrep -x sxhkd > /dev/null || sxhkd &
ksuperkey -e 'Super_L=Super_L|Alt_L|Shift_L|r'
export ZDOTDIR=$HOME/.config/zsh

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Nm-connection-editor state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a MEGAsync state=floating border=off
bspc rule -a firefox desktop=x follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

bspc config window_gap          0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#000000'
bspc config normal_border_color '#000000'
bspc config active_border_color '#000000'
bspc config border_width 1

bspc config focus_follows_pointer true

# input

setxkbmap -layout us,hu -variant ,qwerty -option grp:win_space_toggle caps:swapescape
libinput-gestures-setup start
xset r rate 350 50
xinput --set-prop 9 'libinput Accel Speed' -0.4

# autostart 

bluetoothctl power on
if ! pgrep -x "megasync" > /dev/null
then
    megasync & disown
fi

