[icons]
icons = "awesome6"
[icons.overrides]
bat = ["", "", "", "", ""]

[[block]]
block = "keyboard_layout"
driver = "kbddbus"
format = " $layout "
interval = 15
[block.mappings]
"English (US)" = "us"
"Hungarian (QWERTY)" = "hu"

[[block]]
block = "bluetooth"
mac = "AC:12:2F:6E:29:C7"
disconnected_format = ""
format = " $icon  {$percentage|}"

[[block]]
block = "bluetooth"
mac = "08:EB:ED:20:91:8F"
disconnected_format = ""
format = " $icon  {$percentage |}"

[[block]]
block = "battery"
format = " $icon  $percentage "
charging_format = "   $percentage "
full_format = "   "
not_charging_format = "   $percentage "
empty_format = "   "
missing_format = ""

[[block]]
block = "sound"
format = "{ $icon  $volume.eng(w:2) |}"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# [[block]]
# block = "backlight"
# missing_format = ""
# device = "intel_backlight"
# format = " light: $brightness "

[[block]]
block = "net"
format = " {|󰈀} "
inactive_format = " 󰖪 "
[[block.click]]
button = "left"
cmd = "kitty --class=nmtui nmtui-connect"

[[block]]
block = "time"
interval = 1
[block.format]
full = " $timestamp.datetime(f:'%a %m/%d %H:%M:%S') "
short = " $timestamp.datetime(f:'%H:%M') "
