[icons]
icons = "awesome6"
[icons.overrides]
bat = ["", "", "", "", ""]

[theme]
theme = "native"

[[block]]
block = "keyboard_layout"
driver = "kbddbus"
format = " $layout "
interval = 15
[block.mappings]
"English (US)" = "us"
"Hungarian (QWERTY)" = "hu"

[[block]]
block = "battery"
format = " $icon  $percentage "
charging_format = "   $percentage "
full_format = "   $percentage "
not_charging_format = "   $percentage "
empty_format = "   $percentage "
missing_format = ""

[[block]]
block = "sound"
format = "{ $icon  $volume.eng(w:2) |  Muted}"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# [[block]]
# block = "backlight"
# missing_format = ""
# device = "intel_backlight"
# format = " light: $brightness "

[[block]]
block = "net"
format = "{   $ssid| 󰈀  Wired}"
inactive_format = " 󰖪 "
[[block.click]]
button = "left"
cmd = "kitty --class=nmtui nmtui-connect"

[[block]]
block = "time"
interval = 1
[block.format]
full = " $timestamp.datetime(f:'%a %m/%d %H:%M:%S') "
short = " $timestamp.datetime(f:'%H:%M') "
