[[block]]
block = "keyboard_layout"
driver = "kbddbus"
interval = 15
[block.mappings]
"English (US)" = "us"
"Hungarian (QWERTY)" = "hu"

[[block]]
block = "battery"
format = " bat: $percentage "
charging_format = " bat: $percentage charging "
full_format = " bat: full "
not_charging_format = " bat: full "
empty_format = " bat: empty "
missing_format = ""

# [[block]]
# block = "sound"
# format = " vol: {$volume.eng(w:2) |muted }"
# [[block.click]]
# button = "left"
# cmd = "pavucontrol"

# [[block]]
# block = "backlight"
# missing_format = ""
# device = "intel_backlight"
# format = " light: $brightness "

[[block]]
block = "net"
format = " net: {$ssid|Wired} "
[[block.click]]
button = "left"
cmd = "kitty --class=floating nmtui-connect"

[[block]]
block = "time"
interval = 1
[block.format]
full = " $timestamp.datetime(f:'%a %m/%d %H:%M:%S') "
short = " $timestamp.datetime(f:'%H:%M') "
