#!/bin/sh

alias ls='exa'
alias rm='rm -Ir'
alias cp='cp -i'
alias cd='z'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias hss='hugo server --noHTTPCache'
alias gcc="gcc -Wall -Wextra -lm -o main"
alias diff="diff --strip-trailing-cr -Z"
alias g++="g++ -Wall -Wextra -o main"
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias bat='bat --theme=GitHub'
alias fp="fzf --preview 'bat --style=numbers --color=always --theme=GitHub --line-range :500 {}'"
alias r='sudo $(fc -ln -1)'
alias sync='$HOME/.dotfiles/sync.sh'
alias kom='sudo sshfs -o allow_other p_adhnd@komondor.hpc.kifu.hu:/home/p_adhnd /mnt/komondor -o IdentityFile=/home/bozo/.ssh/id_ed25519'
alias win='sudo grub-reboot 1 && reboot'
