#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="firefox"
path+=/opt/docker-desktop/bin
path+=~/.local/share/gem/ruby/3.0.0/bin
path+=~/.emacs.d/bin
path+=~/.ghcup/bin
path+=~/.local/bin
path+=~/.cabal/bin
export PATH
