#!/bin/sh

alias ls="ls --color=auto"
alias rm='rm -Ir'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias hss='hugo server --noHTTPCache'
alias cleanup='/home/$USER/.dotfiles/cleanup.sh'
alias gcc="gcc -Wall -Wextra -lm -o main"
alias diff="diff --strip-trailing-cr -Z"
alias g++="g++ -Wall -Wextra -o main"
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias bat='bat --theme=GitHub'
alias fp="fzf --preview 'bat --style=numbers --color=always --theme=GitHub --line-range :500 {}'"

